import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function composeEmail(recipient_name: string, query: string, validatedSummary: string): Promise<{subject: string, body: string}> {
  const emailResponse = await ai.models.generateContent({
    model: "gemini-3.1-pro-preview",
    contents: `You are an Email Composer Agent in a multi-agent system.
Convert the following Validated Legal Summary into a professional email deliverable.

Query: ${query}
Validated Summary: ${validatedSummary}

Format strictly as Markdown:

**Subject:** [Clear legal subject line]

---

Dear ${recipient_name || "[Recipient Name]"},

Please find below the structured legal analysis based on your query.

---

### Legal Summary:
[Reformat the validated summary cleanly, preserving the System Note regarding validation]

---

### Key Insights:
- Analysis generated using Swiss Law AI System
- Citations validated before delivery
- [Add any other relevant insights]

---

### Recommendations:
- Verify findings with official Swiss legal counsel
- [Add any specific recommendations]

---

Disclaimer:
*This communication is generated by an AI multi-agent legal system and must be reviewed by a qualified legal professional.*

Sincerely,  
Swiss Law Multi-Agent AI System`
  });
  
  const emailDraft = emailResponse.text;
  if (!emailDraft) throw new Error("No response from AI Email Composer");
  
  let subjectStr = "Swiss Law Analysis Request";
  const subjectMatch = emailDraft.match(/\*\*Subject:\*\*\s*(.+)/);
  if (subjectMatch) {
     subjectStr = subjectMatch[1];
  }
  
  return {
    subject: subjectStr,
    body: emailDraft
  };
}
